[package]
name = "frolicking-with-serdee"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bigdecimal = { version = "0.4.5", features = ["serde"] }
hex = "0.4.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_plain = "1.0.2"
