[package]
name = "port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.213", features = ["derive"] }
thiserror = "1.0.65"
