services:
  reverse-proxy:
    build: ./packages/reverse-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - PORT=$PORT
  backend:
    build: ./packages/backend
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - HYPERBOLIC_API_KEY=$HYPERBOLIC_API_KEY
      - DATABASE_URL=$DATABASE_URL
      - UPLOADTHING_TOKEN=$UPLOADTHING_TOKEN