services:
  reverse-proxy:
    build: ./packages/reverse-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - BACKEND_PORT=$PORT
    networks:
      - app
    volumes:
      - ./packages/reverse-proxy/data/certbot/conf:/etc/letsencrypt
      - ./packages/reverse-proxy/data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./packages/reverse-proxy/data/certbot/conf:/etc/letsencrypt
      - ./packages/reverse-proxy/data/certbot/www:/var/www/certbot
  backend:
    build: ./packages/backend
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - HYPERBOLIC_API_KEY=$HYPERBOLIC_API_KEY
      - DATABASE_URL=$DATABASE_URL
      - UPLOADTHING_TOKEN=$UPLOADTHING_TOKEN
    networks:
      - app
networks:
  app:
    driver: bridge
